### ISSUE TITLE
Implement MongoDB in place of Postgres

### ISSUE THREAD

**Issue by ItsCosmas** [yhagio/go_api_boilerplate#1]
Hi, first all I really like this boilerplate it's really well thought of. However, I'm trying to replicate your same approach with `MongoDB` instead of `Postgres` and inplace I'm using [github.com/Kamva/mgm/v2](https://github.com/Kamva/mgm "Mongo Go Models (mgm) is a fast and simple MongoDB ODM for Go (based on official Mongo Go Driver)") as my `ODM` . Here's my repository file `book_repository.go`

```
package bookrepo

import (
	"go-app/domain/book"

	"github.com/Kamva/mgm/v2"
)

type Repo interface {
	// GetByID(id uint) (*user.User, error)
	// GetByEmail(email string) (*user.User, error)
	CreateBook(book *book.Book) error
	// Update(user *user.User) error
}

// FIXME Bug Here
// In My case I'm not using `gorm`
type bookRepo struct {
	db *gorm.DB
}

// FIXME Fix this error
// NewBookRepo will instantiate Book Repository
func NewBookRepo(db *gorm.DB) Repo {
	return &bookRepo{
		db: db,
	}
}

// CreateBook returns a pointer to a Book Struct that contains specified data
// This function takes a name and pages as parameters,
// and returns a pointer to a Book struct that contains the specified data.
func CreateBook(name string, pages int) *book.Book {
	return &book.Book{
		Name:  name,
		Pages: pages,
	}
}

```

and here is where I set up repositories `app.go`
```

package app

import (
	"go-app/repositories/bookrepo"
	"go-app/services/bookservice"
	"net/http"

	"github.com/Kamva/mgm/v2"
	"go.mongodb.org/mongo-driver/mongo/options"

	"github.com/gin-gonic/gin"

	"go-app/controllers"
)

var (
	r = gin.Default()
)

// Init sets up mgm default config for mongodb
func init() {
	// Setup mgm default config
	err := mgm.SetDefaultConfig(nil, "books_db", options.Client().ApplyURI("mongodb://mongo:27017"))
	if err != nil {
		panic(err)
	}
}

// Run is the App Entry Point
func Run() {
	/*
		====== Setup repositories =======
	*/
	// FIXME - BUG
	bookRepo := bookrepo.NewBookRepo(db)
	/*
		====== Setup services ===========
	*/
	bookService := bookservice.NewBookService(bookRepo)
	/*
		====== Setup controllers ========
	*/
	bookCtl := controllers.NewUserController(bookService)

        // routes
	r.GET("/", func(c *gin.Context) {
		c.JSON(http.StatusOK, gin.H{
			"message": "Welcome to your Gin App on Docker",
		})
	})

	r.POST("/books", bookCtl.PostBook)
	r.Run()
}

```

My main issue is I don't really understand how you are passing `db` while instantiating your Repo. Any help to integrate `mongo` following your approach will be highly appreciated.

**Comment by yhagio** [comment]
Hey @ItsCosmas 
thanks for checking out.

You need to create own mongo struct in mongo repository and its implementation
I just created a branch to illustrate this. Hope this helps.

https://github.com/yhagio/go_api_boilerplate/compare/features/mongodb?expand=1

I'll probably create full implementation when I have time

**Comment by ItsCosmas** [comment]
> Hey @ItsCosmas
> thanks for checking out.
> 
> You need to create own mongo struct in mongo repository and its implementation
> I just created a branch to illustrate this. Hope this helps.
> 
> https://github.com/yhagio/go_api_boilerplate/compare/features/mongodb?expand=1
> 
> I'll probably create full implementation when I have time

Hi, thanks for your response. Integration with MongoDB actually worked based on this branch https://github.com/yhagio/go_api_boilerplate/compare/features/mongodb?expand=1. Cheers!. Also, I'm willing to contribute for the MongoDB implementation.
